context("openbis login")

test_that("openbis login is possible", {
  expect_error(login_openbis())
  expect_error(suppressWarnings(login_openbis("foo", "bar")))
  expect_error(login_openbis(cred$username, cred$password, api = "foo"))
  expect_error(login_openbis(cred$username, cred$password, url = "foo"))
  expect_error(login_openbis("foo", "bar", url = "google.ch"))
  expect_error(login_openbis("foo", "bar", foo = "google.ch"))
  expect_type(token <- login_openbis(cred$username, cred$password,
                                     auto_disconnect = FALSE), "character")
  expect_true(grepl(paste0("^", cred$username), token))
  expect_true(is_token_valid(token))
  expect_null(logout_openbis(token))
  expect_false(is_token_valid(token))
  token <- login_openbis(cred$username, cred$password)
  tok_chr <- as.character(token)
  expect_true(is_token_valid(tok_chr))
  rm(token)
  expect_message(gc(), "please call .+ when no longer using a token")
  expect_false(is_token_valid(tok_chr))
})
